# Generated by Django 2.2.5 on 2021-05-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='dislike',
            field=models.IntegerField(default=0),
        ),
    ]
